services:
  yawcam:
    image: yawcam/yawcam-ai:latest # Use :latest or :edge tag
    container_name: yawcam-ai
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "5995:5995"
    volumes:
      - ./data/.yawcam-ai:/root/.yawcam-ai   # Replace ./data with storage path
      - ./data/videos:/root/yawcam-ai/videos # Replace ./data with storage path
    environment:
      TZ: UTC # Set the timezone as needed, e.g. UTC or Europe/Stockholm